### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property Issues on Magento 2.4.7 / PHP 8.3

### ISSUE THREAD

**Issue by jbrejning** [bambora/checkout-magento-v2.x#51]
Hi,

Are you aware of the following error (bambora.log) from Bambora module and can you please help us fix it :-)

[2024-05-24T08:15:16.973898+00:00] Bambora.ERROR: Bambora Checkout Error - ID: -1 - Deprecated Functionality: Creation of dynamic property Bambora\Online\Model\Api\Checkout\Response\Models\TransactionOperation::$ecis is deprecated in /var/www/xxxxxxxx.dk/public_html/vendor/bambora/module-payment-magento2/Model/Api/Checkout/Merchant.php on line 311 [] []
[2024-05-24T08:15:16.974019+00:00] Bambora.ERROR: Bambora Checkout Error - ID: 328034642870044672 - No answer from Bambora [] []

Best regards, 
Jesper

**Comment by sessan** [comment]
Should be fixed now in the 3.1.1-version.

**Comment by jesperbrejning** [comment]
Nope, it's still not suporting php8.2+

[2025-06-23T08:26:51.875498+00:00] Bambora.ERROR: Worldline Checkout Error - ID: -1 - Deprecated Functionality: Creation of dynamic property Bambora\Online\Model\Api\Checkout\Response\Models\TransactionOperation::$parenttransactionoperationid is deprecated in /var/www/xxxxxxxx.dk/public_html/vendor/bambora/module-payment-magento2/Model/Api/Checkout/Merchant.php on line 323 [] []
